/**1. What are the names of all the countries in the country table?**/
SELECT COUNTRY_name FROM Country

/**2. What is the total number of customers in the customers table?**/
SELECT COUNT(DISTINCT CUSTOMER_ID) as 'Number of customers' FROM Customers

/**3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?**/
SELECT AVG(age) FROM Customers
WHERE can_email = 'yes'

/**4. How many orders were made by customers aged 30 or older?**/
with age_30_cust as 
(
  SELECT customer_id, age FROM Customers
WHERE age >= 30
 )
SELECT COUNT(order_id) as 'Amount of orders'
FROM orders t1 inner join age_30_cust t2 on t1.customer_id = t2.customer_id

/**5. What is the total revenue generated by each product category?**/
select t2.category, ROUND(SUM(t2.price), 2) 'Total Revenue' 
from baskets t1 left join products t2 on t1.product_id = t2.product_id
group by t2.category

/**6. What is the average price of products in the 'food' category?**/
SELECT AVG(price) as 'Average price of products'
FROM products
WHERE category = 'food'

/**7. How many orders were made in each sales channel (sales_channel column) in the orders table?**/
SELECT sales_channel, count(order_id)
FROM orders
group by sales_channel

/**8.What is the date of the latest order made by a customer who can receive marketing emails?**/
with customer_mail as
(
SELECT customer_id 
FROM customers 
WHERE can_email = 'yes'
  )
SELECT MAX(date_shop) 
from orders t1 inner join customer_mail t2 on t1.customer_id = t2.customer_id

/**9. What is the name of the country with the highest number of orders?**/
with top_orders as
(
  SELECT Country_id, 
row_number() over (order by COUNT(order_id) desc, country_id) as 'top_amount' 
FROM Orders
group by country_id
  )
  SELECT t1.country_name 
  from country t1 join top_orders t2 on t1.country_id=t2.country_id
  WHERE t2.top_amount = 1

/**10. What is the average age of customers who made orders in the 'vitamins' product category?**/