/**1. What are the names of all the countries in the country table?**/
SELECT COUNTRY_name FROM Country

/**2. What is the total number of customers in the customers table?**/
SELECT COUNT(DISTINCT CUSTOMER_ID) as 'Number of customers' FROM Customers

/**3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?**/
SELECT AVG(age) FROM Customers
WHERE can_email = 'yes'

/**4. How many orders were made by customers aged 30 or older?**/
with age_30_cust as 
(
  SELECT customer_id, age FROM Customers
WHERE age >= 30
 )
SELECT COUNT(order_id) as 'Amount of orders'
FROM orders t1 inner join age_30_cust t2 on t1.customer_id = t2.customer_id

/**5. What is the total revenue generated by each product category?**/
/**6. What is the average price of products in the 'food' category?**/
/**7. How many orders were made in each sales channel (sales_channel column) in the orders table?**/
/**8.What is the date of the latest order made by a customer who can receive marketing emails?**/
/**9. What is the name of the country with the highest number of orders?**/
/**10. What is the average age of customers who made orders in the 'vitamins' product category?**/