/**1. How many transactions were completed during each marketing campaign?**/
select t1.campaign_name, COUNT(t2.transaction_id) as 'Transactions Amount', t1.product_id, t1.start_date, t1.end_date
from marketing_campaigns t1 join transactions t2 on t1.product_id = t2.product_id
where t2.purchase_date BETWEEN t1.start_date and t1.end_date
group by t1.campaign_name, t1.start_date, t1.end_date, t1.product_id

/**2. Which product had the highest sales quantity?**/
with total_sales as
(
SELECT Product_id, SUM(quantity) 'Sales_Quantity'
FROM Transactions
group by product_id
  )
  SELECT t1.product_name, t2.Sales_Quantity
  FROM sustainable_clothing t1 join total_sales t2 on t1.product_id=t2.product_id
  order by t1.product_id
  
/**3. What is the total revenue generated from each marketing campaign?**/
with campaigns_sales as
(
select t1.campaign_name, t1.product_id, SUM(t2.quantity) as 'Sales_quantity'
from marketing_campaigns t1 join transactions t2 on t1.product_id = t2.product_id
where t2.purchase_date BETWEEN t1.start_date and t1.end_date
group by t1.campaign_name, t1.product_id
)
SELECT t1.campaign_name, ROUND(t2.price * t1.sales_quantity, 2) as 'Total Revenue'
FROM campaigns_sales t1 join sustainable_clothing t2 
on t1.product_id=t2.product_id

/**4. What is the top-selling product category based on the total revenue generated?**/
SELECT t2.category, SUM(t1.quantity * t2.price) as 'Total_revenue'
FROM Transactions t1 join sustainable_clothing t2 on t1.product_id = t2.product_id
group by t2.category
ORDER BY Total_revenue desc LIMIT 1

/**5. Which products had a higher quantity sold compared to the average quantity sold?**/
with total_sales as 
(
SELECT product_id, SUM(quantity) 'Sold_quantity'
FROM Transactions
GROUP BY product_id 
  )
  SELECT product_id, sold_quantity,
  (SELECT AVG(sold_quantity) FROM total_sales) as 'Average_quantity'
  FROM total_sales
  WHERE sold_quantity > average_quantity
  GROUP BY Product_id, sold_quantity, Average_quantity
  
/**6. What is the average revenue generated per day during the marketing campaigns?**/
/**7. What is the percentage contribution of each product to the total revenue?**/
/**8. Compare the average quantity sold during marketing campaigns to outside the marketing campaigns**/
/**9. Compare the revenue generated by products inside the marketing campaigns to outside the campaigns**/
/**10. Rank the products by their average daily quantity sold**/